# Generated by Django 4.2.2 on 2023-06-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_data_inscricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='slug',
        ),
    ]
