# Generated by Django 4.2.2 on 2023-06-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_data_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
